apiVersion: apps/v1
kind: Deployment
metadata:
  name: poi-deployment
  namespace: api-namespace
  labels:
    app: poi
spec:
  replicas: 4
  selector:
    matchLabels:
      app: poi
  template:
    metadata:
      labels:
        app: poi
    spec:
      containers:
      - name: poi
        image: registryrca1339.azurecr.io/poi-jb:1.0
        ports:
        - containerPort: 80
        env:
        - name: SQL_SERVER
          value: sqlserverrca1339.database.windows.net
        volumeMounts:
          - name: secrets-store
            mountPath: "/secrets"
            readOnly: true
      volumes:
      - name: secrets-store
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: keyvault-sql
---
apiVersion: v1
kind: Service
metadata:
  name: poi-service
  namespace: api-namespace
spec:
  type: ClusterIP
  ports: 
  - name: http
    port: 80
    targetPort: 80
  selector:
    app: poi