apiVersion: apps/v1
kind: Deployment
metadata:
  name: tripviewer-deployment
  namespace: web-namespace
  labels:
    app: tripviewer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tripviewer
  template:
    metadata:
      labels:
        app: tripviewer
    spec:
      containers:
      - name: tripviewer
        image: registryrca1339.azurecr.io/tripviewer-jb:1.0
        ports:
        - containerPort: 80
        env:
        - name: TRIPS_API_ENDPOINT
          value: "http://trips-service.api-namespace"
        - name: USERPROFILE_API_ENDPOINT
          value: "http://userprofile-service.api-namespace"
--- 
apiVersion: v1
kind: Service
metadata:
  name: tripviewer-service
  namespace: web-namespace
spec:
  type: ClusterIP
  ports: 
  - name: http
    port: 80
    targetPort: 80
  selector:
    app: tripviewer