apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-java-deployment
  namespace: team8
  labels:
    app: user-java
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-java
  template:
    metadata:
      labels:
        app: user-java
    spec:
      containers:
      - name: user-java
        image: registryrca1339.azurecr.io/user-java-jb:1.0
        ports:
        - containerPort: 80
        env:
        - name: SQL_USER
          valueFrom:
            secretKeyRef:
              name: keyvault-sql
              key: username
        - name: SQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: keyvault-sql
              key: password
        - name: SQL_SERVER
          value: sqlserverrca1339.database.windows.net
---
apiVersion: v1
kind: Service
metadata:
  name: user-java-service
  namespace: team8
spec:
  type: ClusterIP
  ports: 
  - name: http
    port: 80
    targetPort: 80
  selector:
    app: user-java