apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: keyvault-sql
  namespace: api-namespace
spec:
  provider: azure
  parameters:
    keyvaultName: "Team8KeyVault"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: 9e528a49-45af-4fd8-a1bf-5f12608de4b5
    objects:  |
      array:
        - |
          objectName: SqlServerUser
          objectAlias: SQL_USER
          objectType: secret
        - |
          objectName: SqlServerPass
          objectAlias: SQL_PASSWORD
          objectType: secret        
    tenantId: "4202fe92-ed4a-4096-82d5-4660ee261eae"